[package]
name = "spinup"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
fs_extra = "1.2"

[[bin]]
name="spinup"
path="src/main.rs"
